#pour supprimer les. class

#pour compiler les tests d'Autobus
comp:
	javac *.java
#pour executer les tests d'Autobus
exec:
	java -ea Lancer 
#pour compiler les tests de PasagerStandard
#compPassager:
#	javac -cp ./src -d build-tstPassager tstPassager/*.java
#pour executer les tests de PassagerStandard
#execPassager:
#	java -cp build-tstPassager -ea tec.LancerTests 
#compsrc:
#	javac -d build src/tec/*.java
#compsimple:
#	javac -cp ./src -d build recette/*.java
#execsimple:
#	java -cp ./build -ea Simple
